// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Ecu3FnyJKmEkqmm8_ntnK7LwvfKp_vk',
    appId: '1:1053671037599:web:71fa5ae09b4b8ce037e0aa',
    messagingSenderId: '1053671037599',
    projectId: 'dermalyze-ff063',
    authDomain: 'dermalyze-ff063.firebaseapp.com',
    databaseURL: 'https://dermalyze-ff063-default-rtdb.firebaseio.com',
    storageBucket: 'dermalyze-ff063.firebasestorage.app',
    measurementId: 'G-PFNVZV1Y4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8rwIWpZS0PdMCdeh7ruLSOsTJmHOqQI',
    appId: '1:1053671037599:android:cceb26d03c265a5d37e0aa',
    messagingSenderId: '1053671037599',
    projectId: 'dermalyze-ff063',
    databaseURL: 'https://dermalyze-ff063-default-rtdb.firebaseio.com',
    storageBucket: 'dermalyze-ff063.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCKeLpOyllIgK1jZBlnCRvDIMmBEZb5XE',
    appId: '1:1053671037599:ios:e07d27cb14c144bf37e0aa',
    messagingSenderId: '1053671037599',
    projectId: 'dermalyze-ff063',
    databaseURL: 'https://dermalyze-ff063-default-rtdb.firebaseio.com',
    storageBucket: 'dermalyze-ff063.firebasestorage.app',
    iosBundleId: 'com.example.diagnoseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCKeLpOyllIgK1jZBlnCRvDIMmBEZb5XE',
    appId: '1:1053671037599:ios:e07d27cb14c144bf37e0aa',
    messagingSenderId: '1053671037599',
    projectId: 'dermalyze-ff063',
    databaseURL: 'https://dermalyze-ff063-default-rtdb.firebaseio.com',
    storageBucket: 'dermalyze-ff063.firebasestorage.app',
    iosBundleId: 'com.example.diagnoseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Ecu3FnyJKmEkqmm8_ntnK7LwvfKp_vk',
    appId: '1:1053671037599:web:dab3c3d80a2f0c0137e0aa',
    messagingSenderId: '1053671037599',
    projectId: 'dermalyze-ff063',
    authDomain: 'dermalyze-ff063.firebaseapp.com',
    databaseURL: 'https://dermalyze-ff063-default-rtdb.firebaseio.com',
    storageBucket: 'dermalyze-ff063.firebasestorage.app',
    measurementId: 'G-H0Z4Y6D8PB',
  );

}